### ISSUE TITLE
Refactor according to feedback from dev community

### ISSUE THREAD

**Issue by rihp** [dOrgTech/rarible-sdk#17]

**Comment by benefacto** [comment]
Feedback notes I took:
- Matching an and creating a bid is still needed
- Validating orders
- Filtering for fillable orders
- Objects need to be simplified and have a higher level of abstraction; objects passed not be as sophisticated as the items returned; end user flow needs to be emulated with the signature of functions created with very little calls between it: 1. Create item 2. Match order 3. Execute

**Comment by benefacto** [comment]
I feel like this will be addressed in b98cd57
